// otak dari program Website Ramalan Masa Depan

// array ramalan masa depan(Data Array)
const jobs = [
  "Pilot",
  "Masinis",
  "Nahkoda",
  "Dokter",
  "Polisi",
  "Tentara",
  "Pemadam kebakaran",
  "Guru Agama",
  "Guru Matematika",
  "Guru Bahasa Indonesia",
  "Guru Bahasa Inggris",
  "Guru Bahasa Jepang",
  "Guru Ilmu Pengetahuan Alam",
  "Guru Ilmu Pengetahuan Sosial",
  "Guru Olahraga",
  "Guru Seni Budaya",
  "Guru BK",
  "Guru Biologi",
  "Guru Kimia",
  "Guru Fisika",
  "Guru Sejarah",
  "Guru ",
  "Dosen",
  "Pengacara",
  "Pengusaha",
  "Pengusaha sukses",
  "Penjelajah waktu",
  "Penyanyi terkenal",
  "Ilmuwan hebat",
  "Developer AI",
  "Pelukis legendaris",
  "Kang siomay",
  "Pemburu hantu",
  "Pengembara waktu",
  "Petualang antariksa",
  "Pengemudi UFO",
  "Owner restoran",
  "Penjaga hutan",
  "Owner peternakan",
  "Pengemudi truk",
  "Owner toko",
  "Pembuat film",
  "Penulis terkenal",
  "Pengajar",
  "Owner perusahaan",
  "Pembuat game",
  "Atlet terkenal",
  "Pengawal presiden",
  "Pengawal rahasia",
  "Pengemudi taksi",
  "Pengemudi ojek online",
  "Pemburu alien",
  "Owner kafe",
  "Owner salon",
  "Owner bengkel",
  "Owner sekolah",
  "Owner hotel",
  "Owner rumah makan",
  "Owner toko roti",
  "Owner toko buku",
  "Owner toko mainan",
  "Owner toko pakaian",
  "Owner toko sepatu",
  "Owner toko handphone",
  "Owner toko komputer",
  "Owner toko elektronik",
  "Owner toko kue",
  "Owner toko es krim",
  "Owner toko kopi",
  "Owner toko teh",
  "Owner toko susu",
  "Owner toko minuman",
  "Owner toko makanan",
  "Owner toko minyak",
  "Owner toko bensin",
  "Owner toko air mineral",
  "Owner toko air",
  "Owner toko minuman",
  "Owner toko makanan",
  "Owner toko minyak",
  "Owner toko bensin",
  "Owner toko air mineral",
  "Owner toko air",
  "Owner toko minuman",
  "Owner toko makanan",

  "Arsitek",
  "Desainer grafis",
  "Insinyur perangkat lunak",
  "Ahli gizi",
  "Psikolog",
  "Ahli biologi",
  "Ahli kimia",
  "Ahli fisika",
  "Jurnalis",
  "Fotografer",
  "Konsultan bisnis",
  "Manajer proyek",
  "Ahli pemasaran",
  "Ahli keuangan",
  "Akuntan",
  "Perawat",
  "Ahli bedah",
  "Ahli hukum",
  "Pekerja sosial",
  "Teknisi listrik",
  "Teknisi mesin",
  "Pekerja konstruksi",
  "Pekerja kebun",
  "Pekerja pabrik",
  "Pemandu wisata",
  "Koki",
  "Barista",
  "Penyiar radio",
  "Penyiar televisi",
  "Animator",
  "Desainer interior",
  "Ahli SEO",
  "Pengembang web",
  "Spesialis media sosial",
  "Ahli keamanan siber",
  "Petugas imigrasi",
  "Petugas bea cukai",
  "Pekerja kemanusiaan",
  "Relawan",
  "Ahli lingkungan",
  "Ahli meteorologi",
  "Penyelam profesional",
  "Pilot drone",
  "Ahli robotika",
  "Ahli kecerdasan buatan",
  "Pekerja logistik",
  "Manajer sumber daya manusia",
  "Ahli hubungan masyarakat",
  "Penyelidik swasta",
  "Pekerja seni",
  "Pekerja kesehatan mental",
  "Ahli terapi fisik",
  "Ahli terapi okupasi",
  "Pekerja perawatan lansia",
  "Pekerja perawatan anak",
  "Pekerja kebersihan",
  "Pekerja keamanan",
  "Pekerja transportasi",
  "Pekerja pengiriman",
  "Pekerja pemeliharaan",
  "Pekerja perhotelan",
  "Pekerja pariwisata",
  "Pekerja event",
  "Pekerja pemasaran digital",
  "Pekerja penjualan",
  "Pekerja customer service",
  "Pekerja telemarketing",
  "Pekerja riset pasar",
  "Pekerja analisis data",
  "Pekerja pengembangan produk",
  "Pekerja manajemen risiko",
  "Pekerja pengembangan bisnis",
  "Pekerja pengelolaan proyek",
  "Pekerja pengelolaan rantai pasokan",
  "Pekerja pengelolaan kualitas",
  "Pekerja pengelolaan lingkungan",
  "Pekerja pengelolaan energi",
  "Pekerja pengelolaan limbah",
  "Pekerja pengelolaan air",
  "Pekerja pengelolaan sumber daya alam",
  "Pekerja pengelolaan kesehatan dan keselamatan",
  "Pekerja pengelolaan keamanan",
  "Pekerja pengelolaan informasi",
  "Pekerja pengelolaan teknologi informasi",
  "Pekerja pengelolaan sistem",
  "Pekerja pengelolaan jaringan",
  "Pekerja pengelolaan database",
  "Pekerja pengelolaan perangkat keras",
  "Pekerja pengelolaan perangkat lunak",
  "Pekerja pengelolaan aplikasi",
  "Pekerja pengelolaan infrastruktur",
  "Pekerja pengelolaan proyek TI",
  "Pekerja pengelolaan sistem informasi",
  "Pekerja pengelolaan keamanan informasi",
  "Pekerja pengelolaan risiko TI",
  "Pekerja pengelolaan kepatuhan",
  "Pekerja pengelolaan audit",
  "Pekerja pengelolaan keuangan",
  "Pekerja pengelolaan akuntansi",
  "Pekerja pengelolaan pajak",
  "Pekerja pengelolaan investasi",
  "Pekerja pengelolaan asuransi",
  "Pekerja pengelolaan pensiun",
  "Pekerja pengelolaan warisan",
  "Pekerja pengelolaan real estat",
  "Pekerja pengelolaan properti",
  "Pekerja pengelolaan konstruksi",
  "Pekerja pengelolaan fasilitas",
  "Pekerja pengelolaan transportasi",
  "Pekerja pengelolaan logistik",
  "Pekerja pengelolaan distribusi",
  "Pekerja pengelolaan rantai pasokan global",
  "Pekerja pengelolaan hubungan pelanggan",
  "Pekerja pengelolaan pengalaman pelanggan",
  "Pekerja pengelolaan merek",
  "Pekerja pengelolaan produk",
  "Pekerja pengelolaan layanan",
  "Pekerja pengelolaan inovasi",
  "Pekerja pengelolaan perubahan",
  "Pekerja pengelolaan strategi",
  "Pekerja pengelolaan komunikasi",
  "Pekerja pengelolaan hubungan masyarakat",
  "Pekerja pengelolaan media",
  "Pekerja pengelolaan konten",
  "Pekerja pengelolaan kampanye",
  "Pekerja pengelolaan acara",
  "Pekerja pengelolaan pemasaran",
  "Pekerja pengelolaan penjualan",
  "Pekerja pengelolaan distribusi",
  "Pekerja pengelolaan e-commerce",
  "Pekerja pengelolaan pemasaran digital",
  "Pekerja pengelolaan analisis data",
  "Pekerja pengelolaan riset pasar",
  "Pekerja pengelolaan pengembangan produk",
  "Pekerja pengelolaan layanan pelanggan",
  "Pekerja pengelolaan pengalaman pengguna",
  "Pekerja pengelolaan desain",
  "Pekerja pengelolaan pengembangan perangkat lunak",
  "Pekerja pengelolaan pengujian perangkat lunak",
  "Pekerja pengelolaan pemeliharaan perangkat lunak",
  "Pekerja pengelolaan pengembangan aplikasi",
  "Pekerja pengelolaan pengembangan web",
  "Pekerja pengelolaan pengembangan sistem",
  "Pekerja pengelolaan pengembangan jaringan",
  "Pekerja pengelolaan pengembangan database",
  "Pekerja pengelolaan pengembangan infrastruktur",
  "Pekerja pengelolaan pengembangan keamanan",
  "Pekerja pengelolaan pengembangan TI",
  "Pekerja pengelolaan pengembangan teknologi",
  "Pekerja pengelolaan pengembangan inovasi",
  "Pekerja pengelolaan pengembangan strategi",
  "Pekerja pengelolaan pengembangan komunikasi",
  "Pekerja pengelolaan pengembangan hubungan masyarakat",
  "Pekerja pengelolaan pengembangan media",
  "Pekerja pengelolaan pengembangan konten",
  "Pekerja pengelolaan pengembangan kampanye",
  "Pekerja pengelolaan pengembangan acara",
  "Pekerja pengelolaan pengembangan pemasaran",
  "Pekerja pengelolaan pengembangan penjualan",
  "Pekerja pengelolaan pengembangan distribusi",
  "Pekerja pengelolaan pengembangan e-commerce",
  "Pekerja pengelolaan pengembangan pemasaran digital",
  "Pekerja pengelolaan pengembangan analisis data",
  "Pekerja pengelolaan pengembangan riset pasar",
  "Pekerja pengelolaan pengembangan produk",
  "Pekerja pengelolaan pengembangan layanan pelanggan",
  "Pekerja pengelolaan pengembangan pengalaman pengguna",
  "Pekerja pengelolaan pengembangan desain",
  "Pekerja pengelolaan pengembangan perangkat lunak",
  "Pekerja pengelolaan pengembangan pengujian perangkat lunak",
  "Pekerja pengelolaan pengembangan pemeliharaan perangkat lunak",
  "Pekerja pengelolaan pengembangan aplikasi",
  "Pekerja pengelolaan pengembangan web",
  "Pekerja pengelolaan pengembangan sistem",
  "Pekerja pengelolaan pengembangan jaringan",
  "Pekerja pengelolaan pengembangan database",
  "Pekerja pengelolaan pengembangan infrastruktur",
  "Pekerja pengelolaan pengembangan keamanan",
  "Pekerja pengelolaan pengembangan TI",
  "Pekerja pengelolaan pengembangan teknologi",
  "Pekerja pengelolaan pengembangan inovasi",
  "Pekerja pengelolaan pengembangan strategi",
  "Pekerja pengelolaan pengembangan komunikasi",
  "Pekerja pengelolaan pengembangan hubungan masyarakat",
  "Pekerja pengelolaan pengembangan media",
  "Pekerja pengelolaan pengembangan konten",
  "Pekerja pengelolaan pengembangan kampanye",
  "Pekerja pengelolaan pengembangan acara",
  "Pekerja pengelolaan pengembangan pemasaran",
  "Pekerja pengelolaan pengembangan penjualan",
  "Pekerja pengelolaan pengembangan distribusi",
  "Pekerja pengelolaan pengembangan e-commerce",
  "Pekerja pengelolaan pengembangan pemasaran digital",
  "Pekerja pengelolaan pengembangan analisis data",
  "Pekerja pengelolaan pengembangan riset pasar",
  "Pekerja pengelolaan pengembangan produk",
  "Pekerja pengelolaan pengembangan layanan pelanggan",
  "Pekerja pengelolaan pengembangan pengalaman pengguna",
  "Pekerja pengelolaan pengembangan desain",
  "Pekerja pengelolaan pengembangan perangkat lunak",
  "Pekerja pengelolaan pengembangan pengujian perangkat lunak",
  "Pekerja pengelolaan pengembangan pemeliharaan perangkat lunak",
  "Pekerja pengelolaan pengembangan aplikasi",
  "Pekerja pengelolaan pengembangan web",
  "Pekerja pengelolaan pengembangan sistem",
  "Pekerja pengelolaan pengembangan jaringan",
  "Pekerja pengelolaan pengembangan database",
  "Pekerja pengelolaan pengembangan infrastruktur",
  "Pekerja pengelolaan pengembangan keamanan",
  "Pekerja pengelolaan pengembangan TI",
  "Pekerja pengelolaan pengembangan teknologi",
  "Pekerja pengelolaan pengembangan inovasi",
  "Pekerja pengelolaan pengembangan strategi",
  "Pekerja pengelolaan pengembangan komunikasi",
  "Pekerja pengelolaan pengembangan hubungan masyarakat",
  "Pekerja pengelolaan pengembangan media",
  "Pekerja pengelolaan pengembangan konten",
  "Pekerja pengelolaan pengembangan kampanye",
  "Pekerja pengelolaan pengembangan acara",
  "Pekerja pengelolaan pengembangan pemasaran",
  "Pekerja pengelolaan pengembangan penjualan",
  "Pekerja pengelolaan pengembangan distribusi",
  "Pekerja pengelolaan pengembangan e-commerce",
  "Pekerja pengelolaan pengembangan pemasaran digital",
  "Pekerja pengelolaan pengembangan analisis data",
  "Pekerja pengelolaan pengembangan riset pasar",

];

const love = [
  "Akan bertemu soulmate di perjalanan",
  "Akan menikah dengan selebriti",
  "Hubungan yang damai dan romantis",
  "Petualangan cinta yang seru",
  "Kisah cinta bak dongeng",
  "Cinta yang tak terduga",
  "Cinta yang akan bersemi di musim semi",
  "Cinta yang akan berkembang di musim panas",
  "Cinta yang akan mekar di musim gugur",
  "Cinta yang akan bersemi di musim dingin",
  "Cinta yang akan tumbuh di musim hujan",
  "Cinta yang akan berkembang di musim kemarau",
  "Cinta yang akan mekar di musim semi",
  "Cinta yang akan bersemi di musim panas",
  "Cinta yang akan berkembang di musim gugur",
  "Cinta yang akan mekar di musim dingin",
  "Cinta yang akan tumbuh di musim hujan",
  "Cinta yang akan berkembang di musim kemarau",
  "Cinta yang akan mekar di musim semi",
  "Cinta yang akan bersemi di musim panas",
  "Cinta yang akan berkembang di musim gugur",
  "Cinta yang akan mekar di musim dingin",
  "Cinta yang akan tumbuh di musim hujan",
  "Cinta yang akan berkembang di musim kemarau",
  "Cinta yang akan mekar di musim semi",
  "Cinta yang akan bersemi di musim panas",
  "Cinta yang akan berkembang di musim gugur",
  "Cinta yang akan mekar di musim dingin",
  "Cinta yang akan tumbuh di musim hujan",
  "Cinta yang akan berkembang di musim kemarau",
  "Cinta yang akan mekar di musim semi",
  "Cinta yang akan bersemi di musim panas",
  "Cinta yang akan berkembang di musim gugur",
  "Cinta yang akan mekar di musim dingin",
  "Cinta yang akan tumbuh di musim hujan",
  "Cinta yang akan berkembang di musim kemarau",
  "Cinta yang akan mekar di musim semi",
  "Cinta yang akan bersemi di musim panas",
  "Cinta yang akan berkembang di musim gugur",

  "Akan menemukan cinta sejati di tempat yang tak terduga",
  "Cinta yang tumbuh dari persahabatan yang kuat",
  "Akan jatuh cinta pada pandangan pertama di sebuah pesta",
  "Cinta yang terjalin melalui hobi yang sama",
  "Akan bertemu dengan cinta di perjalanan jauh",
  "Cinta yang terjalin melalui surat-surat manis",
  "Akan menemukan cinta di lingkungan kerja",
  "Cinta yang datang setelah melewati masa sulit bersama",
  "Akan bertemu dengan cinta di acara komunitas",
  "Cinta yang terbangun dari pertemuan tak sengaja",
  "Akan menemukan cinta di dunia maya yang berlanjut ke dunia nyata",
  "Cinta yang terjalin saat berbagi mimpi dan harapan",
  "Akan menemukan cinta di antara kerumunan",
  "Cinta yang tumbuh di tengah tantangan dan rintangan",
  "Akan menemukan cinta di tempat yang penuh kenangan",
  "Cinta yang datang setelah perjalanan panjang mencari diri sendiri",
  "Akan menemukan cinta di saat yang paling tidak terduga",
  "Cinta yang terjalin saat berbagi tawa dan air mata",
  "Akan menemukan cinta di tengah perayaan yang meriah",
  "Cinta yang datang dari saling mendukung satu sama lain",
  "Akan menemukan cinta di antara bintang-bintang di malam hari",
  "Cinta yang terjalin melalui pengalaman petualangan bersama",
  "Akan menemukan cinta di saat-saat tenang dan damai",
  "Cinta yang datang setelah saling memahami dan menerima",
  "Akan menemukan cinta di tempat yang penuh keajaiban",
  "Cinta yang terjalin melalui perjalanan spiritual bersama",
  "Akan menemukan cinta di saat-saat penuh harapan",
  "Cinta yang datang dari saling menghargai perbedaan",
  "Akan menemukan cinta di antara buku-buku di perpustakaan",
  "Cinta yang terjalin saat berbagi mimpi dan cita-cita",
  "Akan menemukan cinta di tengah hujan yang romantis",
  "Cinta yang datang setelah saling berjuang untuk satu sama lain",
  "Akan menemukan cinta di tempat yang penuh seni dan kreativitas",
  "Cinta yang terjalin saat berbagi momen-momen kecil",
  "Akan menemukan cinta di antara lagu-lagu yang dinyanyikan bersama",
  "Cinta yang datang dari saling melengkapi satu sama lain",
  "Akan menemukan cinta di saat-saat penuh keajaiban",
  "Cinta yang terjalin melalui perjalanan waktu yang indah",
  "Akan menemukan cinta di tempat yang penuh nostalgia",
  "Cinta yang datang setelah saling berkomitmen untuk masa depan",
  "Akan menemukan cinta di antara senyuman dan tatapan penuh arti",
  "Cinta yang terjalin saat berbagi pengalaman hidup yang berharga",
  "Akan menemukan cinta di saat-saat penuh kehangatan",
  "Cinta yang datang dari saling percaya dan menghargai",
  "Akan menemukan cinta di tempat yang penuh keindahan alam",
  "Cinta yang terjalin saat berbagi impian dan harapan",
  "Akan menemukan cinta di antara bintang-bintang di malam yang cerah",
  "Cinta yang datang setelah saling berjuang untuk kebahagiaan",
  "Akan menemukan cinta di saat-saat penuh keajaiban dan harapan",
];

const hobbies = [
  "Mendaki gunung",
  "Mengoleksi benda antik",
  "Menciptakan musik",
  "Menonton film",
  "Membaca buku",
  "Bermain game",
  "Menulis cerita",
  "Melukis pemandangan",
  "Bersepeda keliling kota",
  "Bermain sepak bola",
  "Bermain basket",
  "Bermain bulu tangkis",
  "Bermain tenis",
  "Bermain badminton",
  "Bermain voli",
  "Bermain golf",
  "Bermain catur",
  "Bermain game online",
  "Bermain game offline",
  "Bermain game mobile",
  "Bermain game console",
  "Bermain game PC",
  "Bermain game PS",
  "Bermain game Xbox",
  "Bermain game Nintendo",
  "Bermain game Sony",
  "Bermain game Microsoft",
  "Bermain game Sega",
  "Bermain game Atari",
  "Bermain game SNK",
  "Bermain game Konami",
  "Bermain game Capcom",
  "Bermain game Bandai",
  "Bermain game Namco",
  "Bermain game Square Enix",
  "Bermain game Bethesda",
  "Bermain game Ubisoft",
  "Bermain game Activision",
  "Bermain game EA",
  "Bermain game Valve",
  "Bermain game Blizzard",
  "Bermain game Riot Games",
  "Bermain game Supercell",
  "Bermain game King",
  "Bermain game Mojang",
  "Bermain game Tencent",
  "Bermain game Netmarble",
  "Bermain game Nexon",
  "Bermain game Square Enix",
  "Bermain game Konami",
  "Bermain game Capcom",
  "Bermain game Bandai",
  "Bermain game Namco",
  "Bermain game Square Enix",
  "Bermain game Bethesda",
  "Bermain game Ubisoft",
  "Bermain game Activision",
  "Bermain game EA",
  "Bermain game Valve",
  "Bermain game Blizzard",
  "Bermain game Riot Games",
  "Bermain game Supercell",
  "Bermain game King",
  "Bermain game Mojang",
  "Bermain game Tencent",
  "Bermain game Netmarble",
  "Bermain game Nexon",
  "Bermain game Square Enix",
  "Bermain",
  "Menjadi content creator",
  "Memasak makanan lezat",
  "Berkebun di planet Mars",
];

// Custom predictions for specific names
const customPredictions = {
  raffael: {
    job: "Fullstack Web Developer",
    love: "Bertemu di hari rabu",
    hobby: "Ngoding dong anjay",
  },

  fidhera: {
    job: "CEO Perusahaan dibidang kecantikan",
    love: "Bertemu di hari kamis",
    hobby: "Bermain musik",
  },

  yahya: {
    job: "Owner toko roti",
    love: "Bertemu di hari jumat",
    hobby: "Bermain game",
  },

  pael: {
    job: "presiden",
    love: "berisik banget bgsttttttttt",
    hobby: "diem ah gasuka ditanya",
  }
};

// store predictions locally
const storedPredictions = {};

function generatePrediction() {
  const name = document.getElementById("nameInput").value;
  if (!name.trim()) {
    alert("Harap masukkan nama Anda!");
    return;
  }

// cek jika nama udah ada di prediksi
  if (storedPredictions[name]) {
    displayPrediction(name, storedPredictions[name]);
    return;
  }

  document.getElementById("loading").classList.remove("hidden");
  document.getElementById("result").classList.add("hidden");

  setTimeout(() => {
    document.getElementById("loading").classList.add("hidden");
    document.getElementById("result").classList.remove("hidden");

    // generate prediksi
    let prediction;
    if (customPredictions[name]) {
      prediction = customPredictions[name];
    } else {
      prediction = {
        job: jobs[Math.floor(Math.random() * jobs.length)],
        love: love[Math.floor(Math.random() * love.length)],
        hobby: hobbies[Math.floor(Math.random() * hobbies.length)],
      };
    }

    // Store the prediction
    storedPredictions[name] = prediction;

    displayPrediction(name, prediction);
  }, 2000); // simulasi loading selama 2 detik
}

function displayPrediction(name, prediction) {
  document.getElementById("nameOutput").textContent = name;
  document.getElementById("jobOutput").textContent = prediction.job;
  document.getElementById("loveOutput").textContent = prediction.love;
  document.getElementById("hobbyOutput").textContent = prediction.hobby;
}

function resetPrediction() {
  document.getElementById("nameInput").value = "";
  document.getElementById("loading").classList.add("hidden");
  document.getElementById("result").classList.add("hidden");
}
